### PR TITLE
add flash on successful workflow dispatch

### LINKED ISSUE #12: feature: provide some feedback after triggering a workflow
Requested by @Biswa96.  Was thinking just adding a generic `flash` message after triggering, since there is *no* feedback from github apis that might be helpful, and that kind of matches what github itself does on their actions page.  I never wrote this down because it would probably only be a line or two of code, but I never did get around to actually doing it, so recording it so it doesn't get forgotten.

### PR DESCRIPTION
**Pull request by jeremyd2019**
This is what I was thinking about to resolve #12 but never got around to.

### CODE REVIEW

**Comment by lazka** [comment]
lgtm

**Comment by jeremyd2019** [comment]
The reason I didn't do these previously is that I have not tested them.  It was kind of a hassle to log into pythonanywhere with the 2 factor auth, and these changes were not worth the trouble, I was waiting for some more substantive change that never came.

**Comment by jeremyd2019** [comment]
Was thinking it might make sense to add a different "failed" message in an `else` clause.  But in every case, error handling in this project is sorely lacking (probably should open a new issue for that).

**Comment by lazka** [comment]
Agreed on the error case (part of #15 I guess), but let's just get this in for now :)

**Pull request merged**
